//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDASDataAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapUserConnection
    {
        public int Id { get; set; }
        public int ConnID { get; set; }
        public int UserID { get; set; }
    
        public virtual tblConnection tblConnection { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
